services:
  - type: web
    name: funny-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: funny-backend-db
          property: connectionString

databases:
  - name: funny-backend-db
    plan: free
